In [13]:
import numpy as np
import pandas as pd

verbs = pd.read_pickle('verbs')

verbs[:20]

        0                                     1
0    6718  {u'spoiler': u'False', u'verbs': 27}
1    2068  {u'spoiler': u'False', u'verbs': 20}
2    7337  {u'spoiler': u'False', u'verbs': 19}
3   14393  {u'spoiler': u'False', u'verbs': 19}
4   14466  {u'spoiler': u'False', u'verbs': 18}
5    7573  {u'spoiler': u'False', u'verbs': 17}
6   10926  {u'spoiler': u'False', u'verbs': 17}
7    1300  {u'spoiler': u'False', u'verbs': 16}
8    2422  {u'spoiler': u'False', u'verbs': 15}
9    3734  {u'spoiler': u'False', u'verbs': 15}
10   4496  {u'spoiler': u'False', u'verbs': 15}
11  12513  {u'spoiler': u'False', u'verbs': 15}
12  13112  {u'spoiler': u'False', u'verbs': 15}
13  13225  {u'spoiler': u'False', u'verbs': 15}
14    703  {u'spoiler': u'False', u'verbs': 14}
15   1264  {u'spoiler': u'False', u'verbs': 14}
16   2450  {u'spoiler': u'False', u'verbs': 14}
17   3679  {u'spoiler': u'False', u'verbs': 14}
18   5899  {u'spoiler': u'False', u'verbs': 14}
19   7705  {u'spoiler': u'False', u'verbs': 14}

In [30]:
read_dict = np.load('genredict.npy').item()

df = pd.DataFrame([read_dict])
df = df.rename(index={0: 'genre'})
df = pd.DataFrame.transpose(df)
df[:10]

                                                                genre
AForAndromeda                               [Drama, Sci-Fi, Thriller]
ALF                                [Comedy, Family, Fantasy, Romance]
AaronStone              [Action, Adventure, Family, Sci-Fi, Thriller]
Absolutely                                                   [Comedy]
AbsolutelyFabulous                                           [Comedy]
AccordingToJim                                      [Comedy, Romance]
AceOfCakes                                               [Reality-TV]
AdamAdamantLives                                  [Adventure, Sci-Fi]
AdventuresInWonderland             [Comedy, Family, Fantasy, Musical]
AfterLately                                                  [Comedy]

In [31]:
read_dict = np.load('runtimedict.npy').item()

df = pd.DataFrame([read_dict])
df = df.rename(index={0: 'runtime'})
df = pd.DataFrame.transpose(df)
df[:10]

                                       runtime
AForAndromeda                             [90]
ALF                                       [97]
AaronStone                             unknown
Absolutely              [UK:30, (28 episodes)]
AbsolutelyFabulous         [30, (24 episodes)]
AccordingToJim                            [30]
AceOfCakes                     [21, (approx.)]
AdamAdamantLives           [50, (29 episodes)]
AdventuresInWonderland                    [30]
AfterLately                            unknown